AWSTemplateFormatVersion: "2010-09-09"
Description: "-"
Parameters:
  DataBaseName:
    Type: String
Resources:
  DataBase:
    Type: "AWS::RDS::DBInstance"
    Properties:
      AllocatedStorage: "20"
      DBInstanceClass: db.t2.micro
      Engine: MySQL
      EngineVersion: "5.7.22"
      MasterUsername: "admin"
      MasterUserPassword: "admin123"
      DBName: !Ref DataBaseName