AWSTemplateFormatVersion: "2010-09-09"
Description: "-"

Parameters:
  DataBaseName:
    Type: String
  DbInstanceIdentifier:
    Type: String
  LambdaFunctionName:
    Type: String
  ApiName:
    Type: String
  S3Name:
    Type: String
  VpcName:
    Type: String

Resources:

  s3:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://data-bucket-063.s3.ap-south-1.amazonaws.com/s3.yaml"
      Parameters:
        S3Name: !Ref S3Name
      TimeoutInMinutes: 10

  Rds:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://data-bucket-063.s3.ap-south-1.amazonaws.com/rds.yaml"
      Parameters:
        DbInstanceIdentifier: !Ref DbInstanceIdentifier
        DataBaseName: !Ref DataBaseName
        PrivateSubnet: !GetAtt Vpc.Outputs.PrivateSubnet
        PrivateSubnet2: !GetAtt Vpc.Outputs.PrivateSubnet2
        LambdaSecurityGroup: !GetAtt Lambda.Outputs.LambdaSecurityGroup
        Vpc: !GetAtt Vpc.Outputs.Vpc
      TimeoutInMinutes: 15

  ApiGateway:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://data-bucket-063.s3.ap-south-1.amazonaws.com/api_gateway.yaml"
      Parameters:
        ApiName: !Ref ApiName
        LambdaFunctionArn: !GetAtt Lambda.Outputs.LambdaFunctionArn
      TimeoutInMinutes: 8

  Lambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://data-bucket-063.s3.ap-south-1.amazonaws.com/lambda.yaml"
      Parameters:
        Vpc: !GetAtt Vpc.Outputs.Vpc
        PrivateSubnet: !GetAtt Vpc.Outputs.PrivateSubnet
        LambdaFunctionName: !Ref LambdaFunctionName
        DbInstanceIdentifier: !Ref DbInstanceIdentifier
      TimeoutInMinutes: 8

  Vpc:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://data-bucket-063.s3.ap-south-1.amazonaws.com/vpc.yaml"
      Parameters:
        VpcName: !Ref VpcName
      TimeoutInMinutes: 8

  Ec2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://data-bucket-063.s3.ap-south-1.amazonaws.com/ec2.yaml"
      Parameters:
        Vpc: !GetAtt Vpc.Outputs.Vpc
        PrivateSubnet: !GetAtt Vpc.Outputs.PrivateSubnet
        PublicSubnet: !GetAtt Vpc.Outputs.PublicSubnet
      TimeoutInMinutes: 8


